using System;
using System.ComponentModel.DataAnnotations;

namespace NetCoreLearning.SchoolLessons.DomainModel
{
    /// <summary>
    /// Represents a student
    /// </summary>
    public class Student
    {
        /// <summary>
        /// Gets or sets the Student database identifier. Auto-generated by the API.
        /// </summary>
        [Required]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or sets the Student name.
        /// </summary>
        [Required]
        [MaxLength(50)]
        public string Name { get; set; }
    }
}
